name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: github.repository == 'FrankBuchholz/EEP_convert_anl3_file'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'

      - name: Build
        run: npm ci

      - name: Remove .gitignore
        run: rm .gitignore

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
